Validate params while creating application (#169)
# Description
This PR adds validation level to the params flag, i.e., passing
unsupported parameters would abort the create operation.

# Testing
```
[root@sagarwal ai-services]# ./bin/ai-services application create temp --template rag --params "ui.port=3000"
Validating the LPAR environment before creating application 'temp'...
✔ Current user is root
✔ LPAR affinity score is above the threshold: 70
✔ Operating system is RHEL with version 9.6
✖ unsupported IBM Power version: Power11 is required
HINT: This tools requires IBM Power11 (ppc64le)
✔ System is registered with RHN
✖ IBM Spyre Accelerator is not attached to the LPAR
HINT: IBM Spyre Accelerator hardware is required but not detected.
⠹ Validating servicereport ...servicereport 2.2.5

Warning: spyre plugin is either invalid or not applicable to this system.

✔ ServiceReport tool has successfully run on the LPAR
Error: bootstrap validation failed: 2 validation check(s) failed
```

```
[root@sagarwal ai-services]# ./bin/ai-services application create temp --template rag --params "ui.prt=3000"
Error: error validating params: unsupported parameter: ui.prt, run 'ai-services application templates' for more help
Usage:
  ai-services application create [name] [flags]
  ```

Signed-off-by: sagarwal-ibm <sagarwal@ibm.com>